package appnet

import (
	"bytes"
	"context"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"vulos/backend/services/packages"
)

// Registry holds the catalog of vetted apps with versioned install recipes.
// The registry defines *what* can be installed and *how* — the AppStore handles
// the actual lifecycle (download, install, uninstall).
//
// Registry file format (registry.json):
//
//	{
//	  "apps": {
//	    "postgres": {
//	      "name": "PostgreSQL",
//	      "vetted": true,
//	      "description": "Relational database",
//	      "category": "database",
//	      "author": "PostgreSQL Global Development Group",
//	      "homepage": "https://postgresql.org",
//	      "versions": {
//	        "16": { "install": "apt-get install -y postgresql-16", ... },
//	        "15": { "install": "apt-get install -y postgresql-15", ... }
//	      }
//	    }
//	  }
//	}
type Registry struct {
	Apps map[string]*RegistryEntry `json:"apps"`
}

// RegistryEntry is a single app in the registry.
//
// Registry signing trust model (REGISTRY-SIGN-01):
//
//	A publisher holds an Ed25519 private key and signs each RegistryEntry.
//	The OS is configured with the publisher's Ed25519 public key via the
//	VULOS_REGISTRY_PUBKEY environment variable (base64-encoded raw 32-byte key).
//
//	When VULOS_REGISTRY_PUBKEY is set:
//	  - Every entry MUST carry a non-empty Signature field.
//	  - VerifyEntrySignature is called before install; missing or invalid
//	    signatures cause the install to fail closed.
//
//	When VULOS_REGISTRY_PUBKEY is NOT set (self-host / standalone):
//	  - Signature verification is skipped entirely.
//	  - The operator trusts their own registry.json directly.
//	  - Self-hosters: generate an Ed25519 keypair (e.g. with `openssl genpkey
//	    -algorithm ed25519`), export the 32-byte raw public key in base64, set
//	    VULOS_REGISTRY_PUBKEY, and sign entries with SignEntry before shipping
//	    the registry.
//
//	The sha256 artifact integrity check (Checksum field on VersionRecipe) is
//	independent and always enforced for binary downloads.
type RegistryEntry struct {
	Name        string                    `json:"name"`
	Vetted      bool                      `json:"vetted"` // true = reviewed and approved by Vula OS team
	Type        string                    `json:"type"`   // "web" (serves HTTP), "desktop" (GUI app, streamed via XvfbBackend), or "service" (background daemon)
	Arch        []string                  `json:"arch"`   // supported architectures (e.g. ["amd64","arm64"]), empty = all
	Description string                    `json:"description"`
	Category    string                    `json:"category"`
	Author      string                    `json:"author"`
	Homepage    string                    `json:"homepage"`
	Icon        string                    `json:"icon"`     // unicode fallback icon
	IconURL     string                    `json:"icon_url"` // URL to download icon from
	Keywords    []string                  `json:"keywords"`
	License     string                    `json:"license"`
	Versions    map[string]*VersionRecipe `json:"versions"`
	// Signature is a base64-encoded Ed25519 signature over the canonical entry
	// JSON (this field excluded). Required when VULOS_REGISTRY_PUBKEY is set.
	// Generated by the registry publisher; verified before every install.
	Signature string `json:"signature,omitempty"`
}

// VersionRecipe defines how to install and run a specific version of an app.
type VersionRecipe struct {
	Install      string            `json:"install"`             // shell command to install (e.g., "apt-get install -y postgresql-16")
	FlatpakID    string            `json:"flatpak_id"`          // Flatpak app ID (e.g., "org.gimp.GIMP") — if set, install/run via Flatpak
	DownloadURL  string            `json:"download_url"`        // static install: URL to download a binary or tar.gz archive
	ArchiveStrip int               `json:"archive_strip"`       // static install: number of leading path components to strip when extracting (tar --strip-components)
	Command      string            `json:"command"`             // how to run it (e.g., "bin/postgres -D data/")
	Port         int               `json:"port"`                // default port the app listens on
	PostInstall  string            `json:"post_install"`        // one-time setup command (e.g., "bin/initdb -D data/")
	Deps         []string          `json:"deps"`                // additional OS package dependencies
	Env          map[string]string `json:"env"`                 // default environment variables
	Permissions  []string          `json:"permissions"`         // required permissions
	Checksum     string            `json:"checksum"`            // sha256 checksum of download (if applicable)
	Singleton    bool              `json:"singleton"`           // only one instance allowed
	AutoStart    bool              `json:"auto_start"`          // start on boot
	Disabled     bool              `json:"_disabled,omitempty"` // true = entry is administratively disabled; install is refused
}

// pipeToShellRe matches curl|bash and wget|bash patterns (pipe-to-shell install anti-pattern).
var pipeToShellRe = regexp.MustCompile(`(?i)\b(curl|wget)\b[^|]*\|\s*(ba)?sh\b`)

// shCPipeRe matches sh -c / bash -c invocations that contain a pipe (covers the sh -c "curl … | bash" shape).
var shCPipeRe = regexp.MustCompile(`(?i)^\s*(ba)?sh\s+-c\s+['"]?[^'"]*\|`)

// rejectPipeToShell returns an error if cmd contains a pipe-to-shell pattern.
// Pipe-to-shell recipes (curl|bash, wget|bash, sh -c "…|bash") allow arbitrary code
// execution from a remote URL with no integrity check and are unconditionally rejected.
func rejectPipeToShell(cmd string) error {
	if pipeToShellRe.MatchString(cmd) {
		return fmt.Errorf("recipe contains a pipe-to-shell pattern (curl|bash / wget|bash) which is a security risk: %q — use a pinned artifact download with a checksum instead", cmd)
	}
	if shCPipeRe.MatchString(cmd) {
		return fmt.Errorf("recipe contains a sh -c pipe pattern which is a security risk: %q — use a pinned artifact download with a checksum instead", cmd)
	}
	return nil
}

// binaryDownloadRe matches recipes that download a binary directly via curl/wget to a file
// (as opposed to piping to a shell or delegating to a package manager).
var binaryDownloadRe = regexp.MustCompile(`(?i)\b(curl|wget)\b`)

// requiresChecksum reports whether an install command downloads a binary directly and
// therefore requires a non-empty Checksum field for integrity verification.
// Package-manager installs (apt-get, pip, npm, gem) and Flatpak installs verify
// integrity through their own signing mechanisms and do not require the Checksum field.
func requiresChecksum(install string) bool {
	if install == "" {
		return false
	}
	// Package-manager keywords — these handle their own integrity.
	pkgMgrRe := regexp.MustCompile(`(?i)\b(apt-get|apt|pip[0-9]*|pip3|npm|yarn|gem|brew|dnf|yum|pacman)\b`)
	if pkgMgrRe.MatchString(install) && !binaryDownloadRe.MatchString(install) {
		return false
	}
	// Pure apt-get lines that also happen to pull a key via curl (e.g. Grafana/Syncthing)
	// only need package manager integrity, not a binary checksum.
	if pkgMgrRe.MatchString(install) {
		return false
	}
	// If the recipe downloads a binary directly (curl/wget writing to a file), checksum is required.
	return binaryDownloadRe.MatchString(install)
}

// validateRecipeSecurity checks a recipe for disallowed patterns and missing checksums.
// It must be called before executing any install or post-install commands.
func validateRecipeSecurity(recipe *VersionRecipe) error {
	if recipe.Disabled {
		return fmt.Errorf("this version entry is disabled and cannot be installed")
	}

	// Reject pipe-to-shell in install and post_install.
	if err := rejectPipeToShell(recipe.Install); err != nil {
		return err
	}
	if err := rejectPipeToShell(recipe.PostInstall); err != nil {
		return err
	}

	// Require checksum when the recipe downloads a binary directly.
	if requiresChecksum(recipe.Install) && strings.TrimSpace(recipe.Checksum) == "" {
		return fmt.Errorf("install recipe downloads a binary directly but has no checksum — " +
			"set a sha256 checksum in the registry entry before installing (SEC-H3)")
	}

	// SECAUDIT2 H1: the static-download path (recipe.DownloadURL set, Install
	// empty) fetches an archive/binary over the network and installs it. It
	// MUST have a sha256 checksum — requiresChecksum() only inspects
	// recipe.Install, so without this an unverified artifact would pass the
	// gate. registry.json is cluster-replicated trust data; never relax this.
	if strings.TrimSpace(recipe.DownloadURL) != "" && strings.TrimSpace(recipe.Checksum) == "" {
		return fmt.Errorf("static download recipe (download_url set) has no checksum — " +
			"set a sha256 checksum in the registry entry before installing (SECAUDIT2-H1)")
	}

	return nil
}

// LatestVersion returns the highest version string for an entry.
// Uses simple lexicographic sorting — versions should use sortable format (e.g., "16.3").
func (e *RegistryEntry) LatestVersion() string {
	if len(e.Versions) == 0 {
		return ""
	}
	versions := make([]string, 0, len(e.Versions))
	for v := range e.Versions {
		versions = append(versions, v)
	}
	sort.Sort(sort.Reverse(sort.StringSlice(versions)))
	return versions[0]
}

// GetRecipe returns the recipe for a specific version, or nil.
func (e *RegistryEntry) GetRecipe(version string) *VersionRecipe {
	if version == "" || version == "latest" {
		version = e.LatestVersion()
	}
	return e.Versions[version]
}

// LoadRegistry reads a registry.json file.
func LoadRegistry(path string) (*Registry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var r Registry
	if err := json.Unmarshal(data, &r); err != nil {
		return nil, err
	}
	if r.Apps == nil {
		r.Apps = make(map[string]*RegistryEntry)
	}
	return &r, nil
}

// envRegistryPubKey is the environment variable that holds the trusted Ed25519
// publisher public key (base64-encoded raw 32-byte key).
const envRegistryPubKey = "VULOS_REGISTRY_PUBKEY"

// LoadTrustedPublicKey reads the Ed25519 publisher public key from
// VULOS_REGISTRY_PUBKEY. Returns nil when the env var is unset (self-host /
// standalone mode: signature verification is skipped — the operator trusts
// their own registry.json directly).
func LoadTrustedPublicKey() ed25519.PublicKey {
	v := strings.TrimSpace(os.Getenv(envRegistryPubKey))
	if v == "" {
		return nil
	}
	raw, err := base64.StdEncoding.DecodeString(v)
	if err != nil {
		log.Printf("[registry] WARNING: %s is set but not valid base64: %v — signature verification disabled", envRegistryPubKey, err)
		return nil
	}
	if len(raw) != ed25519.PublicKeySize {
		log.Printf("[registry] WARNING: %s decoded to %d bytes, expected %d (Ed25519 pubkey) — signature verification disabled", envRegistryPubKey, len(raw), ed25519.PublicKeySize)
		return nil
	}
	return ed25519.PublicKey(raw)
}

// signableEntry returns the canonical JSON bytes over which the Ed25519
// signature is computed. The Signature field is zeroed so the sig covers
// all other entry fields — avoiding the chicken-and-egg problem.
func signableEntry(entry *RegistryEntry) ([]byte, error) {
	tmp := *entry // shallow copy
	tmp.Signature = ""
	return json.Marshal(tmp)
}

// SignEntry computes an Ed25519 signature over the entry (excluding Signature)
// and stores it in entry.Signature (base64-encoded). Used by the registry
// publisher tooling when building or updating registry.json.
func SignEntry(entry *RegistryEntry, privKey ed25519.PrivateKey) error {
	data, err := signableEntry(entry)
	if err != nil {
		return fmt.Errorf("marshal entry for signing: %w", err)
	}
	sig := ed25519.Sign(privKey, data)
	entry.Signature = base64.StdEncoding.EncodeToString(sig)
	return nil
}

// VerifyEntrySignature verifies the Ed25519 publisher signature on entry.
//
//   - pubKey == nil: verification is skipped (returns nil). This is the
//     self-host / standalone mode where the operator trusts their registry.
//   - pubKey set + entry.Signature empty: returns an error (fail-closed).
//   - pubKey set + signature invalid: returns an error (fail-closed).
//
// Both the sha256 artifact Checksum and this signature are verified before
// any install proceeds — they are independent integrity/authenticity layers.
func VerifyEntrySignature(entry *RegistryEntry, pubKey ed25519.PublicKey) error {
	if pubKey == nil {
		return nil // no trusted pubkey configured — self-host mode, skip
	}
	if entry.Signature == "" {
		return fmt.Errorf("registry entry has no publisher signature " +
			"(VULOS_REGISTRY_PUBKEY is configured — all entries must be signed by the trusted publisher)")
	}
	sig, err := base64.StdEncoding.DecodeString(entry.Signature)
	if err != nil {
		return fmt.Errorf("registry entry signature is not valid base64: %w", err)
	}
	if len(sig) != ed25519.SignatureSize {
		return fmt.Errorf("registry entry signature is %d bytes, expected %d (Ed25519)", len(sig), ed25519.SignatureSize)
	}
	data, err := signableEntry(entry)
	if err != nil {
		return fmt.Errorf("marshal entry for verification: %w", err)
	}
	if !ed25519.Verify(pubKey, data, sig) {
		return fmt.Errorf("registry entry signature verification failed — " +
			"entry content may have been tampered with or was signed by a different key")
	}
	return nil
}

// SaveRegistry writes a registry.json file.
func SaveRegistry(path string, r *Registry) error {
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

// InstallFromRegistry installs an app from the registry into appsDir.
// It runs the install command, generates a validated app.json manifest,
// downloads the icon, and runs post_install if present.
func InstallFromRegistry(ctx context.Context, reg *Registry, appID, version, appsDir string) error {
	entry, ok := reg.Apps[appID]
	if !ok {
		return fmt.Errorf("app %q not found in registry", appID)
	}

	if version == "" || version == "latest" {
		version = entry.LatestVersion()
	}
	recipe, ok := entry.Versions[version]
	if !ok {
		return fmt.Errorf("version %q not found for app %q (available: %s)",
			version, appID, strings.Join(availableVersions(entry), ", "))
	}

	// REGISTRY-SIGN-01: verify Ed25519 publisher signature before touching the
	// filesystem. Fails closed when VULOS_REGISTRY_PUBKEY is configured; skipped
	// in self-host / standalone mode (pubkey env var unset).
	if err := VerifyEntrySignature(entry, LoadTrustedPublicKey()); err != nil {
		return fmt.Errorf("registry entry %q failed publisher signature check: %w", appID, err)
	}

	// Security gate: reject disabled entries, pipe-to-shell recipes, and
	// binary downloads with empty checksums before touching the filesystem.
	if err := validateRecipeSecurity(recipe); err != nil {
		return fmt.Errorf("security check failed for %s@%s: %w", appID, version, err)
	}

	appDir := filepath.Join(appsDir, appID)

	// Create strict directory structure
	for _, dir := range []string{"bin", "static", "data"} {
		os.MkdirAll(filepath.Join(appDir, dir), 0755)
	}

	// Flatpak install path
	if recipe.FlatpakID != "" {
		if err := FlatpakInstall(ctx, recipe.FlatpakID); err != nil {
			return fmt.Errorf("flatpak install %s: %w", recipe.FlatpakID, err)
		}
	} else if recipe.DownloadURL != "" {
		// Static (download) install path: download archive/binary, verify checksum, extract into app dir.
		if err := staticInstall(ctx, recipe, appDir); err != nil {
			return fmt.Errorf("static install %s: %w", appID, err)
		}
	} else {
		// Ensure apt cache is ready before installing
		if !packages.CacheReady() {
			log.Printf("[registry] apt cache empty, running apt-get update...")
			if err := exec.CommandContext(ctx, "apt-get", "update", "-qq").Run(); err != nil {
				return fmt.Errorf("apt-get update failed: %w (run 'Update Package Index' from Settings first)", err)
			}
		}

		// Run install command
		if recipe.Install != "" {
			log.Printf("[registry] installing %s@%s: %s", appID, version, recipe.Install)
			var stderrBuf bytes.Buffer
			cmd := exec.CommandContext(ctx, "sh", "-c", recipe.Install)
			cmd.Dir = appDir
			cmd.Stdout = os.Stdout
			cmd.Stderr = &stderrBuf
			home := os.Getenv("HOME")
			if home == "" {
				home = "/root"
			}
			cmd.Env = append(os.Environ(), fmt.Sprintf("APP_DIR=%s", appDir), "HOME="+home)
			if err := cmd.Run(); err != nil {
				errOutput := lastLines(stderrBuf.String(), 10)
				if errOutput != "" {
					return fmt.Errorf("install command failed: %w\n%s", err, errOutput)
				}
				return fmt.Errorf("install command failed: %w", err)
			}
		}
	}

	// Install additional deps
	if len(recipe.Deps) > 0 {
		packages.InstallDeps(ctx, recipe.Deps)
	}

	// Generate the app.json manifest
	appType := entry.Type
	if appType == "" {
		appType = "web"
	}
	appCommand := recipe.Command
	if recipe.FlatpakID != "" && appCommand == "" {
		appCommand = FlatpakRunCommand(recipe.FlatpakID)
	}
	manifest := &AppManifest{
		ID:          appID,
		Name:        entry.Name,
		Icon:        entry.Icon,
		IconPath:    "icon.svg",
		Description: entry.Description,
		Version:     version,
		Command:     appCommand,
		Port:        recipe.Port,
		Type:        appType,
		Category:    entry.Category,
		Keywords:    entry.Keywords,
		Env:         recipe.Env,
		Deps:        recipe.Deps,
		WorkDir:     appDir,
		AutoStart:   recipe.AutoStart,
		Singleton:   recipe.Singleton,
		Permissions: recipe.Permissions,
		Author:      entry.Author,
		License:     entry.License,
		Homepage:    entry.Homepage,
	}

	// Write manifest
	manifestData, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal manifest: %w", err)
	}
	if err := os.WriteFile(filepath.Join(appDir, "app.json"), manifestData, 0644); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}

	// Create a placeholder icon if none exists
	iconPath := filepath.Join(appDir, "icon.svg")
	if _, err := os.Stat(iconPath); os.IsNotExist(err) {
		placeholderIcon := generatePlaceholderIcon(entry.Name, entry.Icon)
		os.WriteFile(iconPath, []byte(placeholderIcon), 0644)
	}

	// Run post-install command
	if recipe.PostInstall != "" {
		log.Printf("[registry] post-install %s: %s", appID, recipe.PostInstall)
		var stderrBuf bytes.Buffer
		cmd := exec.CommandContext(ctx, "sh", "-c", recipe.PostInstall)
		cmd.Dir = appDir
		cmd.Stdout = os.Stdout
		cmd.Stderr = &stderrBuf
		cmd.Env = append(os.Environ(),
			fmt.Sprintf("APP_DIR=%s", appDir),
			fmt.Sprintf("DATA_DIR=%s", filepath.Join(appDir, "data")),
		)
		if err := cmd.Run(); err != nil {
			errOutput := lastLines(stderrBuf.String(), 10)
			if errOutput != "" {
				log.Printf("[registry] post-install warning for %s: %v\n%s", appID, err, errOutput)
			} else {
				log.Printf("[registry] post-install warning for %s: %v", appID, err)
			}
		}
	}

	// Symlink data dir to user data directory
	userDataDir := filepath.Join(os.Getenv("HOME"), ".vulos", "data", appID)
	appDataDir := filepath.Join(appDir, "data")
	if _, err := os.Stat(userDataDir); os.IsNotExist(err) {
		os.MkdirAll(filepath.Dir(userDataDir), 0755)
		// Only symlink if the data dir is empty (fresh install)
		entries, _ := os.ReadDir(appDataDir)
		if len(entries) == 0 {
			os.Remove(appDataDir)
			os.Symlink(userDataDir, appDataDir)
			os.MkdirAll(userDataDir, 0755)
		}
	}

	log.Printf("[registry] installed %s@%s → %s", appID, version, appDir)
	return nil
}

// RegistryList returns a flat list of all registry entries with their IDs,
// suitable for API responses.
type RegistryListEntry struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Type        string   `json:"type"`       // "web", "desktop", or "service"
	Arch        []string `json:"arch"`       // supported architectures, empty = all
	FlatpakID   string   `json:"flatpak_id"` // non-empty if installed via Flatpak
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Author      string   `json:"author"`
	Icon        string   `json:"icon"`
	Vetted      bool     `json:"vetted"`
	Versions    []string `json:"versions"`
	Latest      string   `json:"latest"`
	Installed   bool     `json:"installed"`
	Homepage    string   `json:"homepage"`
	License     string   `json:"license"`
}

// ListEntries returns a flat list of all registry apps, marking which are installed.
// For Flatpak apps, checks the live Flatpak state so removed apps disappear immediately.
func (r *Registry) ListEntries(appsDir string) []RegistryListEntry {
	flatpakApps := InstalledFlatpaks()
	var entries []RegistryListEntry
	for id, entry := range r.Apps {
		versions := availableVersions(entry)
		installed := false
		if _, err := os.Stat(filepath.Join(appsDir, id, "app.json")); err == nil {
			installed = true
		}
		// Sync: if this is a flatpak app, verify it's still actually installed
		if installed {
			if recipe := entry.GetRecipe(entry.LatestVersion()); recipe != nil && recipe.FlatpakID != "" {
				if !flatpakApps[recipe.FlatpakID] {
					// Flatpak was removed externally — clean up stale manifest
					installed = false
					os.RemoveAll(filepath.Join(appsDir, id))
				}
			}
		}
		appType := entry.Type
		if appType == "" {
			appType = "web" // default to web
		}
		// Get flatpak ID from latest recipe
		flatpakID := ""
		if recipe := entry.GetRecipe(entry.LatestVersion()); recipe != nil {
			flatpakID = recipe.FlatpakID
		}
		entries = append(entries, RegistryListEntry{
			ID:          id,
			Name:        entry.Name,
			Type:        appType,
			Arch:        entry.Arch,
			FlatpakID:   flatpakID,
			Description: entry.Description,
			Category:    entry.Category,
			Author:      entry.Author,
			Icon:        entry.Icon,
			Vetted:      entry.Vetted,
			Versions:    versions,
			Latest:      entry.LatestVersion(),
			Installed:   installed,
			Homepage:    entry.Homepage,
			License:     entry.License,
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
	return entries
}

// lastLines returns the last n non-empty lines from s, trimmed.
func lastLines(s string, n int) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	if len(lines) == 0 || (len(lines) == 1 && lines[0] == "") {
		return ""
	}
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n")
}

func availableVersions(entry *RegistryEntry) []string {
	versions := make([]string, 0, len(entry.Versions))
	for v := range entry.Versions {
		versions = append(versions, v)
	}
	sort.Sort(sort.Reverse(sort.StringSlice(versions)))
	return versions
}

// staticInstall downloads a binary or archive from recipe.DownloadURL, verifies its SHA-256
// checksum (when recipe.Checksum is set), and installs it into appDir.
//
//   - .tar.gz / .tgz archives: extracted with tar, stripping recipe.ArchiveStrip leading
//     path components. The caller is expected to set recipe.Command to a path relative to
//     appDir (e.g. "bin/server").
//   - Single binary: saved directly to bin/<basename>, made executable.
//
// The download is streamed so large files do not require buffering in memory.
func staticInstall(ctx context.Context, recipe *VersionRecipe, appDir string) error {
	url := recipe.DownloadURL
	log.Printf("[registry/static] downloading %s", url)

	client := &http.Client{Timeout: 10 * time.Minute}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return fmt.Errorf("build request: %w", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("download: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("download: HTTP %d", resp.StatusCode)
	}

	// Buffer to a temp file so we can verify the checksum before extracting.
	tmpFile, err := os.CreateTemp(appDir, ".dl-*")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpPath := tmpFile.Name()
	defer os.Remove(tmpPath)

	h := sha256.New()
	if _, err := io.Copy(io.MultiWriter(tmpFile, h), resp.Body); err != nil {
		tmpFile.Close()
		return fmt.Errorf("write download: %w", err)
	}
	tmpFile.Close()

	// Verify checksum when provided.
	if recipe.Checksum != "" {
		got := hex.EncodeToString(h.Sum(nil))
		if got != strings.ToLower(recipe.Checksum) {
			return fmt.Errorf("checksum mismatch: expected %s, got %s", recipe.Checksum, got)
		}
		log.Printf("[registry/static] checksum OK (%s)", got[:12])
	}

	// Detect archive vs plain binary by URL extension.
	lowerURL := strings.ToLower(url)
	isArchive := strings.HasSuffix(lowerURL, ".tar.gz") ||
		strings.HasSuffix(lowerURL, ".tgz") ||
		strings.HasSuffix(lowerURL, ".tar.bz2") ||
		strings.HasSuffix(lowerURL, ".tar.xz")

	if isArchive {
		// SECAUDIT2 H1: pre-extraction traversal screen. `tar` does not block
		// `../` / absolute / symlink-escaping members. List members first and
		// refuse any that would escape appDir. Archive-format-agnostic so
		// strip-components and .bz2/.xz keep working; the artifact is already
		// checksum-verified above, this is defense-in-depth on its contents.
		listCmd := exec.CommandContext(ctx, "tar", "tf", tmpPath)
		listOut, lerr := listCmd.Output()
		if lerr != nil {
			return fmt.Errorf("list archive: %w", lerr)
		}
		for _, m := range strings.Split(string(listOut), "\n") {
			m = strings.TrimSpace(m)
			if m == "" {
				continue
			}
			if strings.HasPrefix(m, "/") || strings.HasPrefix(m, "../") ||
				strings.Contains(m, "/../") || m == ".." {
				return fmt.Errorf("refusing archive: unsafe member %q (path traversal)", m)
			}
		}
		args := []string{"xf", tmpPath, "-C", appDir, "--no-same-owner"}
		if recipe.ArchiveStrip > 0 {
			args = append(args, fmt.Sprintf("--strip-components=%d", recipe.ArchiveStrip))
		}
		log.Printf("[registry/static] extracting archive into %s (strip=%d)", appDir, recipe.ArchiveStrip)
		cmd := exec.CommandContext(ctx, "tar", args...)
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("extract archive: %w\n%s", err, strings.TrimSpace(string(out)))
		}
	} else {
		// Plain binary: install to bin/<filename>.
		base := filepath.Base(strings.SplitN(url, "?", 2)[0])
		destPath := filepath.Join(appDir, "bin", base)
		if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
			return fmt.Errorf("create bin dir: %w", err)
		}
		if err := os.Rename(tmpPath, destPath); err != nil {
			// Rename may fail across mount points; fall back to copy.
			if err2 := copyFile(tmpPath, destPath); err2 != nil {
				return fmt.Errorf("install binary: %w", err2)
			}
		}
		if err := os.Chmod(destPath, 0755); err != nil {
			return fmt.Errorf("chmod binary: %w", err)
		}
		log.Printf("[registry/static] installed binary → %s", destPath)
	}

	return nil
}

// copyFile copies src to dst, creating dst if it does not exist.
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

// generatePlaceholderIcon creates a simple SVG icon with the app's unicode icon or first letter.
func generatePlaceholderIcon(name, icon string) string {
	display := icon
	if display == "" && name != "" {
		display = strings.ToUpper(name[:1])
	}
	if display == "" {
		display = "?"
	}
	return fmt.Sprintf(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="14" fill="#1a1a1a"/>
  <text x="32" y="40" text-anchor="middle" font-size="28" fill="#e5e5e5" font-family="system-ui">%s</text>
</svg>`, display)
}
