// crypto.go — E2E encryption for Vula peering messages (PEER-37).
//
// # Overview
//
// This file provides end-to-end encryption for 1-on-1 peering messages and
// CRDT operations.  Two endpoints each hold an Ed25519 identity keypair
// (generated by identity.go); this file derives an X25519 Diffie-Hellman
// keypair from that identity key, performs an X25519 key exchange to produce
// a shared secret, and then uses XChaCha20-Poly1305 for authenticated
// encryption of message payloads.
//
// The Vula servers transport only ciphertext.  Even if a server is
// compromised, message content is unreadable without the recipient's private
// key.
//
// # Cryptographic design
//
//  1. Key derivation — Ed25519 → X25519
//
//     The 64-byte Ed25519 private key is laid out as:
//     [32-byte seed | 32-byte public key]
//     The seed is processed with SHA-512; the first 32 bytes of that hash,
//     clamped per RFC 7748, form the X25519 scalar.  This is the standard
//     Ed25519→X25519 derivation used by libsodium and Signal.
//
//     The corresponding Ed25519 public key is converted to its birationally
//     equivalent Montgomery-form X25519 public key using the standard formula
//     u = (1+y)/(1-y) mod p  (see RFC 7748 Appendix A).
//
//  2. Key exchange — X25519 ECDH
//
//     PeerSharedSecret computes ECDH between the local X25519 private scalar
//     and the remote X25519 public key, then runs HKDF-SHA256 over the raw
//     shared secret, binding it to both Vula IDs in lexicographic order so the
//     same secret is derived by both parties independently.
//
//  3. Per-conversation keys
//
//     ConversationKey derives an X25519 keypair from the caller's Ed25519 key,
//     converts the remote Ed25519 public key to X25519, and returns the
//     HKDF-derived shared key.  Both peers call the same function and obtain
//     the same SharedKey.
//
//  4. Authenticated encryption — XChaCha20-Poly1305
//
//     EncryptForPeer generates a random 24-byte nonce, seals the plaintext with
//     the SharedKey, and prepends the nonce to the ciphertext.  The additional
//     data (AD) string anchors the ciphertext to its semantic context (e.g. the
//     conversation ID) to prevent cross-context replay.
//
//     DecryptFromPeer splits the first 24 bytes as the nonce, then opens the
//     AEAD.  Any truncation, bit-flip, wrong key, or AD mismatch returns an
//     opaque error and nil plaintext (fails closed).
//
// # Public API
//
//	// Key derivation
//	x25519Priv, x25519Pub, err := DeriveX25519FromEd25519(ed25519PrivKey)
//	x25519Pub, err             := Ed25519PubToX25519(ed25519PubKey)
//
//	// Shared secret
//	sharedKey, err := PeerSharedSecret(localX25519Priv, remoteX25519Pub, localVulosID, remoteVulosID)
//
//	// Per-conversation key (convenience — takes raw Ed25519 keys)
//	convKey, err := ConversationKey(localEd25519Priv, remoteEd25519Pub, localVulosID, remoteVulosID)
//
//	// Encrypt / decrypt
//	ciphertext, err := EncryptForPeer(sharedKey, plaintext, additionalData)
//	plaintext, err  := DecryptFromPeer(sharedKey, ciphertext, additionalData)
package peering

import (
	"crypto"
	"crypto/ed25519"
	"crypto/rand"
	_ "crypto/sha256" // register SHA-256 for HKDF
	"crypto/sha512"
	"errors"
	"fmt"
	"math/big"

	"golang.org/x/crypto/chacha20poly1305"
	"golang.org/x/crypto/curve25519"
	"golang.org/x/crypto/hkdf"
)

// ─── Package-level constants ──────────────────────────────────────────────────

const (
	// x25519ScalarSize is the size (bytes) of an X25519 scalar or public key.
	x25519ScalarSize = curve25519.ScalarSize // 32

	// peerSharedKeySize is the length of the HKDF-derived key used with
	// XChaCha20-Poly1305.
	peerSharedKeySize = chacha20poly1305.KeySize // 32

	// xchacha20NonceSz is the nonce length for XChaCha20-Poly1305.
	xchacha20NonceSz = chacha20poly1305.NonceSizeX // 24

	// hkdfLabel is the HKDF "info" context label for all peer key derivations.
	hkdfLabel = "vula-peering-x25519-v1"
)

// hkdfHashFunc is the hash function used in HKDF.
var hkdfHashFunc = crypto.SHA256.New

// fieldPrime is p = 2^255 - 19, the field modulus for Curve25519.
var fieldPrime = func() *big.Int {
	p := new(big.Int).Lsh(big.NewInt(1), 255)
	p.Sub(p, big.NewInt(19))
	return p
}()

// ─── Key types ────────────────────────────────────────────────────────────────

// X25519PrivateKey is a 32-byte X25519 scalar (clamped per RFC 7748).
type X25519PrivateKey [x25519ScalarSize]byte

// X25519PublicKey is the 32-byte X25519 public key (Montgomery u-coordinate).
type X25519PublicKey [x25519ScalarSize]byte

// SharedKey is a 32-byte symmetric key derived from X25519 ECDH + HKDF-SHA256.
// It is ready to use as an XChaCha20-Poly1305 key.
type SharedKey [peerSharedKeySize]byte

// ─── Key derivation: Ed25519 → X25519 ────────────────────────────────────────

// DeriveX25519FromEd25519 derives an X25519 keypair from an Ed25519 private key.
//
// The derivation follows the standard RFC 7748 / libsodium approach:
//  1. Take the 32-byte seed (first half of the 64-byte ed25519.PrivateKey).
//  2. Hash the seed with SHA-512.
//  3. Use the first 32 bytes of the digest as the X25519 scalar.
//  4. Clamp the scalar per RFC 7748 §5.
//  5. Compute the corresponding X25519 public key via ScalarBaseMult.
//
// This is the same derivation used by libsodium's
// crypto_sign_ed25519_sk_to_curve25519 and by Signal.
func DeriveX25519FromEd25519(edPriv ed25519.PrivateKey) (X25519PrivateKey, X25519PublicKey, error) {
	if len(edPriv) != ed25519.PrivateKeySize {
		return X25519PrivateKey{}, X25519PublicKey{}, fmt.Errorf(
			"peering/crypto: ed25519 private key: got %d bytes, want %d",
			len(edPriv), ed25519.PrivateKeySize,
		)
	}

	// Step 1–2: SHA-512 of the 32-byte seed.
	h := sha512.Sum512(edPriv[:32])

	// Step 3–4: clamp the scalar.
	var scalar [x25519ScalarSize]byte
	copy(scalar[:], h[:32])
	scalar[0] &= 248  // clear bits 0, 1, 2
	scalar[31] &= 127 // clear bit 255
	scalar[31] |= 64  // set bit 254

	priv := X25519PrivateKey(scalar)

	// Step 5: derive the public key.
	pubBytes, err := curve25519.X25519(priv[:], curve25519.Basepoint)
	if err != nil {
		return X25519PrivateKey{}, X25519PublicKey{}, fmt.Errorf("peering/crypto: scalar base mult: %w", err)
	}

	var pub X25519PublicKey
	copy(pub[:], pubBytes)
	return priv, pub, nil
}

// Ed25519PubToX25519 converts an Ed25519 public key to its corresponding
// X25519 (Montgomery-form) public key.
//
// The conversion uses the birational map between the Edwards and Montgomery
// curves (RFC 7748 Appendix A, libsodium crypto_sign_ed25519_pk_to_curve25519):
//
//	u = (1 + y) / (1 - y)  mod p
//
// where y is the Edwards y-coordinate encoded in the public key (little-endian,
// sign bit cleared), and p = 2^255 - 19.
func Ed25519PubToX25519(edPub ed25519.PublicKey) (X25519PublicKey, error) {
	if len(edPub) != ed25519.PublicKeySize {
		return X25519PublicKey{}, fmt.Errorf(
			"peering/crypto: ed25519 public key: got %d bytes, want %d",
			len(edPub), ed25519.PublicKeySize,
		)
	}

	// Decode the Edwards y-coordinate (LE, sign bit cleared).
	var edY [32]byte
	copy(edY[:], edPub)
	edY[31] &= 0x7f // clear sign bit (bit 255)

	// Convert from little-endian bytes to big.Int.
	y := le32ToBigInt(&edY)

	one := big.NewInt(1)

	// numer = (1 + y) mod p
	numer := new(big.Int).Add(one, y)
	numer.Mod(numer, fieldPrime)

	// denom = (1 - y) mod p  — ensure non-negative.
	denom := new(big.Int).Sub(fieldPrime, y)
	denom.Add(denom, one)
	denom.Mod(denom, fieldPrime)

	// denom_inv = denom^(p-2) mod p  (Fermat's little theorem).
	exp := new(big.Int).Sub(fieldPrime, big.NewInt(2))
	denomInv := new(big.Int).Exp(denom, exp, fieldPrime)

	// u = numer * denom_inv mod p.
	u := new(big.Int).Mul(numer, denomInv)
	u.Mod(u, fieldPrime)

	// Encode as 32-byte little-endian.
	var rawPub [32]byte
	bigIntToLE32(&rawPub, u)
	return X25519PublicKey(rawPub), nil
}

// ─── Shared secret ────────────────────────────────────────────────────────────

// PeerSharedSecret computes the X25519 ECDH shared secret between the local
// private key and the remote public key, then derives a 32-byte symmetric key
// with HKDF-SHA256.
//
// The HKDF salt is the concatenation of the two Vula IDs in lexicographic
// order (guaranteed to be the same on both sides of the conversation):
//
//	salt = sort(localVulosID, remoteVulosID)[0] + ":" + sort(...)[1]
//
// The HKDF info string is the package-level hkdfLabel constant.
//
// Both peers call this function with swapped local/remote arguments and
// obtain the same SharedKey because:
//   - ECDH is commutative: X25519(a, B) == X25519(b, A)
//   - The salt construction sorts the IDs deterministically
func PeerSharedSecret(
	localPriv X25519PrivateKey,
	remotePub X25519PublicKey,
	localVulosID, remoteVulosID string,
) (SharedKey, error) {
	// ECDH.
	rawSecret, err := curve25519.X25519(localPriv[:], remotePub[:])
	if err != nil {
		return SharedKey{}, fmt.Errorf("peering/crypto: x25519 ecdh: %w", err)
	}

	// Sort the Vula IDs to produce a deterministic salt.
	idA, idB := localVulosID, remoteVulosID
	if idA > idB {
		idA, idB = idB, idA
	}
	salt := []byte(idA + ":" + idB)

	// HKDF-SHA256.
	r := hkdf.New(hkdfHashFunc, rawSecret, salt, []byte(hkdfLabel))
	var key SharedKey
	if _, err := r.Read(key[:]); err != nil {
		return SharedKey{}, fmt.Errorf("peering/crypto: hkdf read: %w", err)
	}
	return key, nil
}

// ConversationKey is a convenience wrapper that:
//  1. Derives an X25519 keypair from the local Ed25519 private key.
//  2. Converts the remote Ed25519 public key to X25519.
//  3. Calls PeerSharedSecret.
//
// Both endpoints call ConversationKey with their own keys and the peer's
// public key and independently arrive at the same SharedKey.
//
// The additionalData parameter is included in the HKDF salt via
// PeerSharedSecret's vulosID pair, so callers should pass the relevant
// conversation/context identifier through EncryptForPeer / DecryptFromPeer
// rather than here.
func ConversationKey(
	localEdPriv ed25519.PrivateKey,
	remoteEdPub ed25519.PublicKey,
	localVulosID, remoteVulosID string,
) (SharedKey, error) {
	localX25519Priv, _, err := DeriveX25519FromEd25519(localEdPriv)
	if err != nil {
		return SharedKey{}, fmt.Errorf("peering/crypto: derive local x25519: %w", err)
	}

	remoteX25519Pub, err := Ed25519PubToX25519(remoteEdPub)
	if err != nil {
		return SharedKey{}, fmt.Errorf("peering/crypto: convert remote ed25519 pub to x25519: %w", err)
	}

	return PeerSharedSecret(localX25519Priv, remoteX25519Pub, localVulosID, remoteVulosID)
}

// ─── Encrypt / Decrypt ────────────────────────────────────────────────────────

// EncryptForPeer encrypts plaintext with key using XChaCha20-Poly1305.
//
// A random 24-byte nonce is generated and prepended to the ciphertext:
//
//	output = nonce (24 bytes) || AEAD.Seal(plaintext, additionalData)
//
// additionalData binds the ciphertext to its semantic context (e.g. a
// conversation ID or message type).  The same string must be supplied to
// DecryptFromPeer.  May be empty but must not be nil.
func EncryptForPeer(key SharedKey, plaintext, additionalData []byte) ([]byte, error) {
	aead, err := chacha20poly1305.NewX(key[:])
	if err != nil {
		return nil, fmt.Errorf("peering/crypto: create xchacha20poly1305: %w", err)
	}

	nonce := make([]byte, xchacha20NonceSz)
	if _, err := rand.Read(nonce); err != nil {
		return nil, fmt.Errorf("peering/crypto: generate nonce: %w", err)
	}

	ciphertext := aead.Seal(nil, nonce, plaintext, additionalData)

	// Prepend nonce.
	out := make([]byte, xchacha20NonceSz+len(ciphertext))
	copy(out[:xchacha20NonceSz], nonce)
	copy(out[xchacha20NonceSz:], ciphertext)
	return out, nil
}

// DecryptFromPeer decrypts a ciphertext produced by EncryptForPeer.
//
// The ciphertext must be at least 24+16 bytes:
//
//	ciphertext = nonce (24 bytes) || AEAD ciphertext (≥16 bytes tag)
//
// Any truncation, corruption, wrong key, or additionalData mismatch causes
// decryption to fail closed — a non-nil error is returned and the returned
// plaintext is nil.
func DecryptFromPeer(key SharedKey, ciphertext, additionalData []byte) ([]byte, error) {
	minLen := xchacha20NonceSz + chacha20poly1305.Overhead
	if len(ciphertext) < minLen {
		return nil, errors.New("peering/crypto: ciphertext too short")
	}

	aead, err := chacha20poly1305.NewX(key[:])
	if err != nil {
		return nil, fmt.Errorf("peering/crypto: create xchacha20poly1305: %w", err)
	}

	nonce := ciphertext[:xchacha20NonceSz]
	body := ciphertext[xchacha20NonceSz:]

	plaintext, err := aead.Open(nil, nonce, body, additionalData)
	if err != nil {
		// Return an opaque error — do not leak whether the key or the data was wrong.
		return nil, errors.New("peering/crypto: decryption failed")
	}
	return plaintext, nil
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// le32ToBigInt interprets a 32-byte little-endian array as a non-negative
// integer.
func le32ToBigInt(b *[32]byte) *big.Int {
	// big.Int.SetBytes expects big-endian, so reverse.
	tmp := make([]byte, 32)
	for i, v := range b {
		tmp[31-i] = v
	}
	return new(big.Int).SetBytes(tmp)
}

// bigIntToLE32 encodes n as a 32-byte little-endian array into dst.
func bigIntToLE32(dst *[32]byte, n *big.Int) {
	be := n.Bytes()
	for i := range dst {
		dst[i] = 0
	}
	// be is big-endian; write to dst in reverse (little-endian).
	for i, v := range be {
		dst[len(be)-1-i] = v
	}
}
