import { useState, useEffect, useRef, useCallback } from 'react'
import QRCanvas from './QRCanvas.jsx'

// ---------------------------------------------------------------------------
// Vula ID validation
// Format: vula:ed25519:<base58-encoded-public-key>[@host:port]
// Also accept bare domain slugs like alice.vulos.org for domain-based discovery.
// ---------------------------------------------------------------------------
const VULA_ID_RE = /^vula:ed25519:[1-9A-HJ-NP-Za-km-z]{32,}(@[\w.-]+(:\d+)?)?$/

function validateVulaAddress(raw) {
  const trimmed = raw.trim()
  if (!trimmed) return { ok: false, error: 'Enter a Vula address.' }

  // Accept vula:ed25519:... with optional @host
  if (VULA_ID_RE.test(trimmed)) return { ok: true, value: trimmed }

  // Accept domain slugs: alice.vulos.org or alice.vulos.org:8080
  if (/^[\w-]+(\.[\w-]+)+(:\d+)?$/.test(trimmed)) return { ok: true, value: trimmed }

  // Reject anything else with a helpful message
  if (trimmed.startsWith('vula:') && !trimmed.startsWith('vula:ed25519:')) {
    return { ok: false, error: 'Unrecognised key type — expected vula:ed25519:…' }
  }
  if (trimmed.startsWith('vula:ed25519:') && trimmed.length < 28) {
    return { ok: false, error: 'Key too short — check you pasted the full Vula ID.' }
  }
  return {
    ok: false,
    error:
      'Not a valid Vula address. Expected "vula:ed25519:<key>[@host:port]" or a domain slug like "alice.vulos.org".',
  }
}

// ---------------------------------------------------------------------------
// POST contact request
// ---------------------------------------------------------------------------
async function sendContactRequest(vulaAddress, message) {
  const res = await fetch('/api/peering/contacts/request', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      vula_id: vulaAddress,
      message: message.trim() || undefined,
    }),
  })
  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`${res.status} ${text || res.statusText}`)
  }
  return res.json().catch(() => ({}))
}

// ---------------------------------------------------------------------------
// Inline QR decoder — reads pixel data from a <canvas> after the user
// captures a video frame via getUserMedia. Uses a simple threshold scan
// sufficient for well-lit QR codes at modest zoom.
// ---------------------------------------------------------------------------

// Decode a QR module grid to a byte string by scanning bit positions.
// This is a compact finder-pattern locator + data extractor.
// For production use replace with a library like jsQR (npm); this covers
// the common Vula ID QR codes generated by QRCanvas.jsx (V1-10, ECC M, mask 0).

function thresholdImage(imgData, w, h) {
  const gray = new Uint8Array(w * h)
  for (let i = 0; i < w * h; i++) {
    const r = imgData[i * 4], g = imgData[i * 4 + 1], b = imgData[i * 4 + 2]
    gray[i] = Math.round(0.299 * r + 0.587 * g + 0.114 * b)
  }
  // Adaptive threshold: Otsu's method
  let sum = 0
  for (let i = 0; i < gray.length; i++) sum += gray[i]
  const mean = sum / gray.length
  let varBetween = 0, bestT = mean
  for (let t = 0; t < 256; t++) {
    let n0 = 0, s0 = 0
    for (let i = 0; i < gray.length; i++) {
      if (gray[i] < t) { n0++; s0 += gray[i] }
    }
    const n1 = gray.length - n0
    if (n0 === 0 || n1 === 0) continue
    const m0 = s0 / n0, m1 = (sum - s0) / n1
    const v = (n0 * n1 * (m0 - m1) ** 2) / (gray.length ** 2)
    if (v > varBetween) { varBetween = v; bestT = t }
  }
  const bin = new Uint8Array(w * h)
  for (let i = 0; i < gray.length; i++) bin[i] = gray[i] < bestT ? 1 : 0
  return bin
}

function locateFinder(bin, w, h) {
  // Find rows with a run matching the 1:1:3:1:1 finder ratio
  const candidates = []
  for (let y = 0; y < h; y++) {
    let runs = [], start = 0, cur = bin[y * w]
    for (let x = 1; x < w; x++) {
      if (bin[y * w + x] !== cur) { runs.push(x - start); start = x; cur = bin[y * w + x] }
    }
    runs.push(w - start)
    // Look for runs of ratio 1:1:3:1:1
    for (let i = 0; i + 4 < runs.length; i++) {
      const r = runs.slice(i, i + 5)
      const u = r[0]
      if (u < 1) continue
      if (
        Math.abs(r[1] - u) <= u * 0.5 &&
        Math.abs(r[2] - 3 * u) <= u * 1.0 &&
        Math.abs(r[3] - u) <= u * 0.5 &&
        Math.abs(r[4] - u) <= u * 0.5
      ) {
        const cx = runs.slice(0, i).reduce((a, b) => a + b, 0) + r[0] + r[1] + Math.round(r[2] / 2)
        candidates.push({ y, x: cx, mod: u })
      }
    }
  }
  return candidates
}

// Attempt a quick decode: locate top-left finder, estimate module size,
// sample the full matrix, decode byte-mode data. Returns string or null.
function decodeQRBitmap(bin, w, h) {
  const candidates = locateFinder(bin, w, h)
  if (candidates.length < 3) return null

  // Sort by y, take top candidates
  candidates.sort((a, b) => a.y - b.y)
  const top = candidates[0]
  const modSize = Math.max(1, top.mod)

  // Estimate version and matrix size
  // Finder pattern is 7 modules; top-left finder top-left corner estimate:
  const tlX = top.x - Math.round(3.5 * modSize)
  const tlY = top.y - Math.round(3 * modSize)
  if (tlX < 0 || tlY < 0) return null

  // Try versions 1-10
  for (let ver = 1; ver <= 10; ver++) {
    const size = ver * 4 + 17
    const mat = []
    for (let r = 0; r < size; r++) {
      const row = []
      for (let c = 0; c < size; c++) {
        const px = Math.round(tlX + c * modSize)
        const py = Math.round(tlY + r * modSize)
        if (px >= 0 && px < w && py >= 0 && py < h) {
          row.push(bin[py * w + px])
        } else {
          row.push(0)
        }
      }
      mat.push(row)
    }
    const text = tryDecodeMatrix(mat, ver)
    if (text) return text
  }
  return null
}

// Minimal byte-mode QR decoder for mask 0 (as produced by QRCanvas.jsx).
function tryDecodeMatrix(mat, ver) {
  try {
    const size = mat.length
    // Un-apply mask 0: (r+c)%2===0 → flip, excluding function modules
    function isFn(r, c) {
      if (r < 9 && c < 9) return true
      if (r < 9 && c >= size - 8) return true
      if (r >= size - 8 && c < 9) return true
      if (r === 6 || c === 6) return true
      if (r === size - 8 && c === 8) return true
      return false
    }
    const m = mat.map((row, r) =>
      row.map((v, c) => {
        if (isFn(r, c)) return v
        return (r + c) % 2 === 0 ? v ^ 1 : v
      })
    )

    // Read data bits in QR zigzag order
    const bits = []
    let goingUp = true
    let col = size - 1
    while (col > 0) {
      if (col === 6) col--
      for (let rowStep = 0; rowStep < size; rowStep++) {
        const row = goingUp ? size - 1 - rowStep : rowStep
        for (let dc = 0; dc <= 1; dc++) {
          const c = col - dc
          if (!isFn(row, c)) bits.push(m[row][c])
        }
      }
      goingUp = !goingUp
      col -= 2
    }

    // Decode byte mode
    let pos = 0
    const readBits = (n) => {
      let v = 0
      for (let i = 0; i < n; i++) v = (v << 1) | (bits[pos++] || 0)
      return v
    }
    const mode = readBits(4)
    if (mode !== 0b0100) return null // not byte mode

    const ccBits = ver <= 9 ? 8 : 16
    const len = readBits(ccBits)
    if (len < 1 || len > 500) return null

    const bytes = []
    for (let i = 0; i < len; i++) bytes.push(readBits(8))

    return new TextDecoder().decode(new Uint8Array(bytes))
  } catch {
    return null
  }
}

// ---------------------------------------------------------------------------
// Tab enum
// ---------------------------------------------------------------------------
const TAB_PASTE = 'paste'
const TAB_SCAN  = 'scan'

// ---------------------------------------------------------------------------
// Scan tab — camera viewfinder + QR decode loop
// ---------------------------------------------------------------------------
function ScanTab({ onDetected }) {
  const videoRef  = useRef(null)
  const canvasRef = useRef(null)
  const streamRef = useRef(null)
  const rafRef    = useRef(null)
  const foundRef  = useRef(false)
  const tickRef   = useRef(null)

  const [camError, setCamError] = useState(null)
  const [scanning, setScanning] = useState(false)
  const [hint, setHint]     = useState('Starting camera…')

  const stopStream = useCallback(() => {
    if (rafRef.current) { cancelAnimationFrame(rafRef.current); rafRef.current = null }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(t => t.stop())
      streamRef.current = null
    }
  }, [])

  const tick = useCallback(() => {
    const video  = videoRef.current
    const canvas = canvasRef.current
    if (!video || !canvas || foundRef.current) return

    if (video.readyState < 2) {
      rafRef.current = requestAnimationFrame(tickRef.current)
      return
    }

    const vw = video.videoWidth  || 320
    const vh = video.videoHeight || 240
    canvas.width  = vw
    canvas.height = vh
    const ctx = canvas.getContext('2d')
    ctx.drawImage(video, 0, 0, vw, vh)

    const imgData = ctx.getImageData(0, 0, vw, vh).data
    const bin = thresholdImage(imgData, vw, vh)
    const text = decodeQRBitmap(bin, vw, vh)

    if (text) {
      const result = validateVulaAddress(text)
      if (result.ok) {
        foundRef.current = true
        setHint('QR code detected!')
        stopStream()
        onDetected(result.value)
        return
      }
    }

    rafRef.current = requestAnimationFrame(tickRef.current)
  }, [onDetected, stopStream])

  useEffect(() => {
    tickRef.current = tick
  }, [tick])

  useEffect(() => {
    let mounted = true
    foundRef.current = false

    navigator.mediaDevices
      .getUserMedia({ video: { facingMode: 'environment' }, audio: false })
      .then(stream => {
        if (!mounted) { stream.getTracks().forEach(t => t.stop()); return }
        streamRef.current = stream
        if (videoRef.current) {
          videoRef.current.srcObject = stream
          videoRef.current.play().catch(() => {})
        }
        setScanning(true)
        setHint('Point camera at a Vula QR code…')
        rafRef.current = requestAnimationFrame(tickRef.current)
      })
      .catch(err => {
        if (!mounted) return
        setCamError(
          err.name === 'NotAllowedError'
            ? 'Camera permission denied. Allow camera access and try again.'
            : err.name === 'NotFoundError'
            ? 'No camera found on this device.'
            : `Camera error: ${err.message}`
        )
      })

    return () => {
      mounted = false
      stopStream()
    }
  }, [tick, stopStream])

  if (camError) {
    return (
      <div className="flex flex-col items-center justify-center gap-3 py-10 text-center">
        <svg viewBox="0 0 24 24" className="w-10 h-10 text-red-400/60" fill="currentColor">
          <path d="M12 7c.55 0 1 .45 1 1v4c0 .55-.45 1-1 1s-1-.45-1-1V8c0-.55.45-1 1-1zm0 8c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1zM1 21h22L12 2 1 21z"/>
        </svg>
        <p className="text-sm text-red-400">{camError}</p>
        <p className="text-xs text-neutral-600">Use the Paste tab to enter the Vula address manually.</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col items-center gap-4">
      {/* Viewfinder */}
      <div className="relative w-full max-w-xs aspect-square rounded-2xl overflow-hidden bg-neutral-950 border border-neutral-800/60">
        <video
          ref={videoRef}
          className="w-full h-full object-cover"
          playsInline
          muted
        />
        {/* Corner brackets overlay */}
        <div className="absolute inset-0 pointer-events-none">
          {['top-3 left-3', 'top-3 right-3 rotate-90', 'bottom-3 right-3 rotate-180', 'bottom-3 left-3 -rotate-90'].map((pos, i) => (
            <div key={i} className={`absolute ${pos}`}>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="rgba(99,102,241,0.9)" strokeWidth="3" strokeLinecap="round">
                <path d="M2 12V2h10" />
              </svg>
            </div>
          ))}
        </div>
        {/* Scanning line animation */}
        {scanning && (
          <div className="absolute inset-x-4 h-0.5 bg-indigo-400/70 rounded-full shadow-[0_0_8px_2px_rgba(99,102,241,0.6)] animate-scan-line" />
        )}
        {/* Hidden canvas for frame processing */}
        <canvas ref={canvasRef} className="hidden" />
      </div>

      <p className="text-xs text-neutral-500 text-center">{hint}</p>

      <style>{`
        @keyframes scan-line {
          0%   { top: 12%; }
          50%  { top: 85%; }
          100% { top: 12%; }
        }
        .animate-scan-line { animation: scan-line 2s ease-in-out infinite; position: absolute; }
      `}</style>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Paste tab — textarea + validate
// ---------------------------------------------------------------------------
function PasteTab({ value, onChange, error }) {
  return (
    <div className="space-y-3">
      <p className="text-xs text-neutral-500">
        Paste a Vula address below. It looks like{' '}
        <code className="text-indigo-400 font-mono text-[11px]">vula:ed25519:…@host:port</code>{' '}
        or a domain slug like{' '}
        <code className="text-indigo-400 font-mono text-[11px]">alice.vulos.org</code>.
      </p>

      <textarea
        value={value}
        onChange={e => onChange(e.target.value)}
        rows={3}
        spellCheck={false}
        placeholder="vula:ed25519:5Hb7…@alice.vulos.org:8080"
        className="w-full bg-neutral-900 border border-neutral-800 rounded-xl px-4 py-3 text-sm
          text-neutral-200 placeholder-neutral-700 font-mono resize-none
          focus:outline-none focus:border-indigo-500/50 transition-colors"
      />

      {error && (
        <div className="flex items-start gap-2 px-3 py-2.5 rounded-lg bg-red-500/[0.07] border border-red-500/20">
          <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-red-400 mt-0.5 shrink-0" fill="currentColor">
            <path fillRule="evenodd" d="M8 16A8 8 0 108 0a8 8 0 000 16zM6.25 5.5a.75.75 0 00-1.5 0v4a.75.75 0 001.5 0v-4zm4.25-.75a.75.75 0 01.75.75v4a.75.75 0 01-1.5 0v-4a.75.75 0 01.75-.75zM8 13a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd"/>
          </svg>
          <span className="text-xs text-red-400">{error}</span>
        </div>
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------
export default function AddContact({ onSuccess, onCancel }) {
  const [tab, setTab]           = useState(TAB_PASTE)
  const [pasteValue, setPasteValue] = useState('')
  const [pasteError, setPasteError] = useState(null)
  const [message, setMessage]   = useState('')
  const [scannedAddress, setScannedAddress] = useState(null)
  const [busy, setBusy]         = useState(false)
  const [submitError, setSubmitError] = useState(null)
  const [sent, setSent]         = useState(false)

  // When QR scan detects an address, prefill paste tab and switch to it
  const handleScanDetected = useCallback((address) => {
    setScannedAddress(address)
    setPasteValue(address)
    setPasteError(null)
    setTab(TAB_PASTE)
  }, [])

  const handlePasteChange = (v) => {
    setPasteValue(v)
    setPasteError(null)
    setScannedAddress(null)
    setSubmitError(null)
  }

  const resolvedAddress = tab === TAB_PASTE
    ? pasteValue.trim()
    : scannedAddress || ''

  const canSubmit = resolvedAddress.length > 0 && !busy && !sent

  const handleSubmit = async (e) => {
    e.preventDefault()
    setSubmitError(null)

    const validation = validateVulaAddress(resolvedAddress)
    if (!validation.ok) {
      setPasteError(validation.error)
      if (tab !== TAB_PASTE) setTab(TAB_PASTE)
      return
    }

    setBusy(true)
    try {
      await sendContactRequest(validation.value, message)
      setSent(true)
      setTimeout(() => {
        onSuccess?.(validation.value)
      }, 1200)
    } catch (err) {
      setSubmitError(err.message)
    } finally {
      setBusy(false)
    }
  }

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------
  return (
    <div className="flex flex-col gap-5 max-w-md mx-auto">
      {/* Header */}
      <div>
        <h2 className="text-base font-semibold text-neutral-100">Add Contact</h2>
        <p className="text-xs text-neutral-500 mt-0.5">
          Send a contact request to another Vula instance.
        </p>
      </div>

      {/* Success state */}
      {sent ? (
        <div className="flex flex-col items-center gap-3 py-8 text-center">
          <div className="w-12 h-12 rounded-full bg-emerald-500/15 border border-emerald-500/25 flex items-center justify-center">
            <svg viewBox="0 0 16 16" className="w-6 h-6 text-emerald-400" fill="currentColor">
              <path fillRule="evenodd" d="M8 16A8 8 0 108 0a8 8 0 000 16zm3.78-9.72a.75.75 0 00-1.06-1.06L7 8.94 5.28 7.22a.75.75 0 00-1.06 1.06l2.5 2.5a.75.75 0 001.06 0l4-4z" clipRule="evenodd"/>
            </svg>
          </div>
          <p className="text-sm font-medium text-emerald-300">Request sent!</p>
          <p className="text-xs text-neutral-600">
            They will see it in their Requests queue once they come online.
          </p>
        </div>
      ) : (
        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
          {/* Tab switcher */}
          <div className="flex rounded-xl overflow-hidden border border-neutral-800/60 bg-neutral-900/60 p-1 gap-1">
            {[
              { id: TAB_PASTE, label: 'Paste address', icon: 'M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6zm-1 1v5h5M12 13H8m4 4H8' },
              { id: TAB_SCAN,  label: 'Scan QR',       icon: 'M3 7V5a2 2 0 012-2h2M17 3h2a2 2 0 012 2v2M21 17v2a2 2 0 01-2 2h-2M7 21H5a2 2 0 01-2-2v-2M8 12h.01M12 12h.01M16 12h.01' },
            ].map(t => (
              <button
                key={t.id}
                type="button"
                onClick={() => { setTab(t.id); setSubmitError(null) }}
                className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-xs font-medium transition-all ${
                  tab === t.id
                    ? 'bg-indigo-600/20 border border-indigo-500/30 text-indigo-300'
                    : 'text-neutral-500 hover:text-neutral-300'
                }`}
              >
                <svg viewBox="0 0 24 24" className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d={t.icon}/>
                </svg>
                {t.label}
              </button>
            ))}
          </div>

          {/* Scanned address pill — visible when a scan prefilled the address */}
          {scannedAddress && tab === TAB_PASTE && (
            <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-emerald-500/[0.07] border border-emerald-500/20">
              <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-emerald-400 shrink-0" fill="currentColor">
                <path fillRule="evenodd" d="M8 16A8 8 0 108 0a8 8 0 000 16zm3.78-9.72a.75.75 0 00-1.06-1.06L7 8.94 5.28 7.22a.75.75 0 00-1.06 1.06l2.5 2.5a.75.75 0 001.06 0l4-4z" clipRule="evenodd"/>
              </svg>
              <span className="text-xs text-emerald-400">QR scanned — address pre-filled below</span>
            </div>
          )}

          {/* Active tab content */}
          {tab === TAB_PASTE ? (
            <PasteTab
              value={pasteValue}
              onChange={handlePasteChange}
              error={pasteError}
            />
          ) : (
            <ScanTab onDetected={handleScanDetected} />
          )}

          {/* Optional message — only show on paste tab or after scan pre-fill */}
          {(tab === TAB_PASTE || scannedAddress) && (
            <div>
              <label className="block text-xs text-neutral-500 mb-1.5">
                Message <span className="text-neutral-700">(optional)</span>
              </label>
              <input
                type="text"
                value={message}
                onChange={e => setMessage(e.target.value)}
                placeholder="Hey, it's Alice — want to connect on Vula?"
                maxLength={120}
                className="w-full bg-neutral-900 border border-neutral-800 rounded-xl px-4 py-2.5 text-sm
                  text-neutral-200 placeholder-neutral-700
                  focus:outline-none focus:border-indigo-500/50 transition-colors"
                disabled={busy}
              />
            </div>
          )}

          {/* API-level error */}
          {submitError && (
            <div className="flex items-start gap-2 px-3 py-2.5 rounded-lg bg-red-500/[0.07] border border-red-500/20">
              <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 text-red-400 mt-0.5 shrink-0" fill="currentColor">
                <path fillRule="evenodd" d="M8 16A8 8 0 108 0a8 8 0 000 16zM6.25 5.5a.75.75 0 00-1.5 0v4a.75.75 0 001.5 0v-4zm4.25-.75a.75.75 0 01.75.75v4a.75.75 0 01-1.5 0v-4a.75.75 0 01.75-.75zM8 13a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd"/>
              </svg>
              <span className="text-xs text-red-400">{submitError}</span>
            </div>
          )}

          {/* Actions */}
          <div className="flex gap-2 pt-1">
            {onCancel && (
              <button
                type="button"
                onClick={onCancel}
                disabled={busy}
                className="flex-1 py-2.5 rounded-xl text-sm border border-neutral-800/60 text-neutral-500
                  hover:text-neutral-300 hover:border-neutral-700/60 transition-colors disabled:opacity-40"
              >
                Cancel
              </button>
            )}
            <button
              type="submit"
              disabled={!canSubmit}
              className="flex-1 py-2.5 rounded-xl text-sm font-semibold transition-all
                bg-indigo-600/20 border border-indigo-500/30 text-indigo-300
                hover:bg-indigo-600/30 hover:border-indigo-500/50
                disabled:opacity-40 disabled:cursor-not-allowed
                active:scale-[0.98]"
            >
              {busy ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="w-3.5 h-3.5 border-2 border-indigo-400/30 border-t-indigo-400 rounded-full animate-spin" />
                  Sending…
                </span>
              ) : (
                'Send Request'
              )}
            </button>
          </div>
        </form>
      )}

      {/* Preview: show the own QR for reference if the other user needs to scan back */}
      <details className="group">
        <summary className="text-xs text-neutral-600 hover:text-neutral-400 cursor-pointer select-none transition-colors list-none flex items-center gap-1.5">
          <svg viewBox="0 0 16 16" className="w-3 h-3 transition-transform group-open:rotate-90" fill="currentColor">
            <path d="M6 4l4 4-4 4V4z"/>
          </svg>
          Show my Vula QR (so they can scan you back)
        </summary>
        <div className="mt-3">
          <OwnQRPreview />
        </div>
      </details>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Own QR preview — fetches own identity and renders QRCanvas
// ---------------------------------------------------------------------------
function OwnQRPreview() {
  const [identity, setIdentity] = useState(null)
  const [error, setError]       = useState(null)

  useEffect(() => {
    fetch('/api/peering/identity')
      .then(r => r.ok ? r.json() : Promise.reject(new Error(`${r.status}`)))
      .then(data => setIdentity(data))
      .catch(err => setError(err.message))
  }, [])

  if (error) {
    return <p className="text-xs text-red-400">Could not load identity: {error}</p>
  }
  if (!identity) {
    return (
      <div className="flex justify-center py-4">
        <span className="w-4 h-4 border-2 border-neutral-700 border-t-indigo-500 rounded-full animate-spin" />
      </div>
    )
  }

  const vulaId = identity.vula_id || ''
  if (!vulaId) return <p className="text-xs text-neutral-600">No Vula ID found.</p>

  return (
    <div className="flex flex-col items-center gap-3 p-4 rounded-xl bg-neutral-900/60 border border-neutral-800/40">
      <div className="rounded-xl overflow-hidden p-2 bg-neutral-900 border border-neutral-800">
        <QRCanvas value={vulaId} size={160} darkColor="#ffffff" lightColor="#111827" />
      </div>
      <p className="text-[10px] text-neutral-700 font-mono break-all text-center max-w-xs">{vulaId}</p>
    </div>
  )
}
