import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import {
  deriveContentPubKeyB64,
  seal,
  open,
  isSealed,
  sealedKIDs,
  parseSealed,
  packMeta,
  unpackMeta,
  untar,
} from '../lib/contentSeal.js'

// Fixture generated by the Go reference implementation:
//   cd backend && go test ./services/files/ -run TestGoJSFixture -v
// It locks the VSEAL1 wire format so the browser (this code) and the Go cell/box
// agree byte-for-byte.
const FIX = {
  recipMasterHex: '1111111111111111111111111111111111111111111111111111111111111111',
  recipPubB64: 'Y5DLT0WlcfYTe6rR9OONEiA+IH1r76m7gTx2TpLcQzw=',
  blobB64:
    'VlNFQUwxCgAAATZ7InYiOjEsImFlYWQiOiJBRVMtMjU2LUdDTSIsImtkZiI6IkhLREYtU0hBMjU2Iiwia2VtIjoiWDI1NTE5IiwiY25vbmNlIjoieWhUa2NzdTk5OGM1MExTQyIsIndyYXBzIjpbeyJraWQiOiJZNURMVDBXbGNmWVRlNnJSOU9PTkVpQStJSDFyNzZtN2dUeDJUcExjUXp3PSIsImVwayI6ImxuWXkrSzkxNk50WTRkKzBmd1FJNjZPTlN1NUpPRWRUOFJpOGlSZ2N4Z2s9Iiwid25vbmNlIjoiZEwzekVzM2M3aFkxRmlzRiIsIndjdCI6InlmdDh3QjBpeEEvcE02WjMrSXBIeE5IY0V6SVoyWjZNdkwvRG91c0loMEk4aWgyb3JnbWpjV1B5ZnIrOGVVckkifV19MUgVIyf1RlkSkGbO6IrRI2cEu23dInNz2mcROgKgB/k=',
  plaintext: 'go-sealed-for-js',
}

function hexToBytes(hex) {
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  return out
}
function b64ToBytes(b64) {
  const bin = atob(b64)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}
function randMaster() {
  return globalThis.crypto.getRandomValues(new Uint8Array(32))
}

describe('contentSeal Go<->JS parity', () => {
  it('derives the same content pubkey as Go from the same master key', async () => {
    const got = await deriveContentPubKeyB64(hexToBytes(FIX.recipMasterHex))
    expect(got).toBe(FIX.recipPubB64)
  })

  it('opens a blob sealed by the Go reference implementation', async () => {
    const blob = b64ToBytes(FIX.blobB64)
    expect(isSealed(blob)).toBe(true)
    const pt = await open(blob, hexToBytes(FIX.recipMasterHex))
    expect(new TextDecoder().decode(pt)).toBe(FIX.plaintext)
  })
})

describe('contentSeal round trip', () => {
  it('seals to recipient + sharer and both can open', async () => {
    const sharer = randMaster()
    const recipient = randMaster()
    const sharerPub = await deriveContentPubKeyB64(sharer)
    const recipPub = await deriveContentPubKeyB64(recipient)
    const msg = new TextEncoder().encode('cell must not read this')
    const blob = await seal(msg, [recipPub, sharerPub])

    expect(new TextDecoder().decode(await open(blob, recipient))).toBe('cell must not read this')
    expect(new TextDecoder().decode(await open(blob, sharer))).toBe('cell must not read this')
  })

  it('a stranger cannot open (fail closed)', async () => {
    const recipient = randMaster()
    const stranger = randMaster()
    const recipPub = await deriveContentPubKeyB64(recipient)
    const blob = await seal(new TextEncoder().encode('secret'), [recipPub])
    await expect(open(blob, stranger)).rejects.toThrow()
  })

  it('tampered ciphertext fails closed', async () => {
    const recipient = randMaster()
    const recipPub = await deriveContentPubKeyB64(recipient)
    const blob = await seal(new TextEncoder().encode('secret bytes'), [recipPub])
    blob[blob.length - 1] ^= 0xff
    await expect(open(blob, recipient)).rejects.toThrow()
  })

  it('refuses to seal to nobody', async () => {
    await expect(seal(new TextEncoder().encode('x'), [])).rejects.toThrow()
  })

  it('sealedKIDs exposes only recipient key-ids (content-blind)', async () => {
    const recipient = randMaster()
    const recipPub = await deriveContentPubKeyB64(recipient)
    const blob = await seal(new TextEncoder().encode('hello world'), [recipPub])
    expect(sealedKIDs(blob)).toEqual([recipPub])
    // header carries no plaintext
    const { header } = parseSealed(blob)
    expect(JSON.stringify(header)).not.toContain('hello')
  })
})

describe('sealed metadata (VMETA1) + folder untar', () => {
  it('packs metadata into the sealed body; cell sees no filename', async () => {
    const recipient = randMaster()
    const recipPub = await deriveContentPubKeyB64(recipient)
    const payload = new TextEncoder().encode('SECRET spreadsheet bytes')
    const packed = packMeta({ name: 'Quarterly Results.xlsx', content_type: 'application/vnd.ms-excel' }, payload)
    const blob = await seal(packed, [recipPub])
    // Filename must not appear anywhere in the ciphertext envelope.
    expect(new TextDecoder('latin1').decode(blob)).not.toContain('Quarterly')
    // Recipient recovers metadata + payload on decrypt.
    const { meta, payload: got } = unpackMeta(await open(blob, recipient))
    expect(meta.name).toBe('Quarterly Results.xlsx')
    expect(meta.content_type).toBe('application/vnd.ms-excel')
    expect(meta.is_dir).toBe(false)
    expect(new TextDecoder().decode(got)).toBe('SECRET spreadsheet bytes')
  })

  it('legacy plaintext (no VMETA1) unpacks with null metadata', () => {
    const raw = new TextEncoder().encode('legacy raw bytes')
    const { meta, payload } = unpackMeta(raw)
    expect(meta).toBe(null)
    expect(new TextDecoder().decode(payload)).toBe('legacy raw bytes')
  })

  it('untars a Go archive/tar fixture (folder round-trip parity)', () => {
    // Produced by Go archive/tar: Project/{readme.txt="hello", sub/data.bin=[1,2,3]}
    const fixB64 = readFileSync('src/__tests__/__fixtures__/folder.tar.b64', 'utf8').trim()
    const bytes = b64ToBytes(fixB64)
    const entries = untar(bytes).filter((e) => !e.isDir)
    const byName = Object.fromEntries(entries.map((e) => [e.name, e.bytes]))
    expect(new TextDecoder().decode(byName['Project/readme.txt'])).toBe('hello')
    expect(Array.from(byName['Project/sub/data.bin'])).toEqual([1, 2, 3])
  })
})
