// Code generated by scripts/wiregen (go run ./scripts/wiregen), invoked via
// `npm run gen:wire-types`. DO NOT EDIT — edit the Go source below and
// regenerate instead.
//
// Source types (see the `targets` slice in scripts/wiregen/main.go to add more):
//   clusterHealthResponse   backend/cmd/server/health.go            GET /api/health
//   Endpoint, Status        backend/services/reach/reach.go         GET /api/network/reach -> "endpoints"
//   LinkState, LinkStatus   backend/services/reach/tunnel/agent.go  GET /api/network/reach -> "links"
//
// The /api/network/reach response itself is `{ enabled: boolean, endpoints: Status[], links: LinkStatus[] }`
// — an inline Go map literal (reachwire.go), not a named type, so it has no
// generated declaration here; see registerReachStatus in
// backend/cmd/server/reachwire.go.
//
// How Go fields became these properties (encoding/json's own rules):
//   - the `json:"name"` tag is the wire property name (fields with no tag keep
//     their exact Go name, which none of these do); `json:"-"` fields are dropped
//   - `,omitempty` makes the TS property optional (`?:`) — Go omits the key
//     entirely rather than sending a zero value
//   - a Go `type X string` with a matching `const` block becomes a TS
//     string-literal union, not a bare `string`
//   - `time.Time` encodes as an RFC3339 string via encoding/json's default
//     MarshalJSON — never a JS Date
//
// TS export capitalised from Go's unexported `clusterHealthResponse`.
export interface ClusterHealthResponse {
  status: string
  checks: Record<string, string>
  timestamp: string
}

export interface Endpoint {
  /** BaseURL is the relay's https base URL, e.g. "https://relay.example.com". No trailing slash (Load normalises). A path component is allowed, for a relay served under a prefix by someone's reverse proxy. */
  url: string
  /** Name is the DNS-label-safe name this box claims on that relay. It becomes the public host, e.g. "box1" -> https://box1.relay.example.com. */
  name: string
  /** Token is the bearer grant the relay authorised this box's Name with. SECRET: never logged, never serialised back out by Public(). */
  token: string
  /** Region is an optional operator label ("eu-central") used only for display and for preferring a nearby relay. Never interpreted. */
  region?: string
  /** Priority orders preference; lower is tried first. Equal priorities keep configuration order. Defaults to configuration order when unset. */
  priority?: number
}

export interface Status {
  endpoint: Endpoint
  healthy: boolean
  failures?: number
  last_error?: string
  /** DownForSeconds is how much longer this endpoint stays in backoff. */
  down_for_seconds?: number
  /** LastOKUnix is when this endpoint last succeeded (0 = never). */
  last_ok_unix?: number
}

export type LinkState =
  | "connecting" // LinkConnecting: dialling or handshaking.
  | "up" // LinkUp: the tunnel is established and serving.
  | "backoff" // LinkBackoff: the last attempt failed; waiting to retry.
  | "refused" // LinkRefused: the relay permanently refused this configuration. The link keeps retrying, but slowly and loudly — see permanentRetry.
  | "stopped" // LinkStopped: the agent is shutting down.

export interface LinkStatus {
  label: string
  name: string
  state: LinkState
  public_url?: string
  last_error?: string
  /** Since is when the link entered its current state. */
  since: string
  /** Attempts is the count of consecutive failed connect attempts. */
  attempts?: number
  /** DirectAccepted reports whether the relay verified and is advertising this box's optional direct endpoint. */
  direct_accepted?: boolean
}

