// byo_keys.go — BYO Mail X25519 public key storage for the keydir package.
//
// This file extends the keydir SQLite store with a separate table for BYO
// (bring-your-own) mail encryption keys. These keys are the X25519 public
// keys generated by the self-hosted vulos-mail binary (vulos-mail keygen).
//
// The control plane stores ONLY the public key. The private key is never
// transmitted to or stored by Vulos.
//
// Table: byo_pubkeys
//
//	account_id     TEXT PK — cp auth account ID (BYO customer)
//	age_pubkey     TEXT    — age X25519 public key (bech32, starts with "age1")
//	fingerprint    TEXT    — first 16 hex chars of SHA-256(bech32-body)
//	uploaded_at    TEXT    — RFC3339 UTC of most recent upload
//	rotation_count INTEGER — increments on each new key upload
//
// Key rotation: uploading a new key replaces the current one and increments
// rotation_count. The agequeue holds blobs encrypted to the *previous* key
// until they are delivered or swept. Mail arriving after the rotation is
// encrypted to the new key. The forwarder always uses the current key from
// this table.
package keydir

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"
)

// Sentinel errors for BYO key operations.
var (
	// ErrBYOKeyNotFound is returned when no BYO key exists for the account.
	ErrBYOKeyNotFound = errors.New("keydir: BYO key not found")

	// ErrInvalidAgeKey is returned when the provided key is not a valid age X25519 public key.
	ErrInvalidAgeKey = errors.New("keydir: invalid age X25519 public key")
)

// byoMigrationSQL creates the byo_pubkeys table if it does not exist.
// It is idempotent and safe to run against an existing database.
const byoMigrationSQL = `
CREATE TABLE IF NOT EXISTS byo_pubkeys (
    account_id     TEXT    NOT NULL PRIMARY KEY,
    age_pubkey     TEXT    NOT NULL,
    fingerprint    TEXT    NOT NULL,
    uploaded_at    TEXT    NOT NULL,
    rotation_count INTEGER NOT NULL DEFAULT 0
);
`

// BYOKeyEntry holds a BYO mail encryption public key record.
type BYOKeyEntry struct {
	AccountID     string
	AgePubkey     string // e.g. "age1xxxxxxxxx..."
	Fingerprint   string // 16-char hex prefix of SHA-256(bech32-body)
	UploadedAt    time.Time
	RotationCount int
}

// BYOHistoryEntry is a single row from the rotation history view.
// In the current schema, only the most-recent key is kept in byo_pubkeys.
// For a full history, a future migration would add a byo_pubkey_history table.
// This type is used by ListBYOKeyHistory's current lightweight implementation.
type BYOHistoryEntry struct {
	AgePubkey     string
	Fingerprint   string
	UploadedAt    time.Time
	RotationCount int
}

// ---------------------------------------------------------------------------
// BYO key methods on SQLStore
// ---------------------------------------------------------------------------

// ensureBYOTable runs the byo_pubkeys migration idempotently.
func (s *SQLStore) ensureBYOTable() error {
	_, err := s.db.Exec(byoMigrationSQL)
	return err
}

// PutBYOKey stores or replaces the BYO X25519 public key for an account.
// It validates that the key starts with "age1" (age X25519 bech32 format),
// computes the fingerprint, and increments rotation_count on each call.
func (s *SQLStore) PutBYOKey(ctx context.Context, accountID, agePubkey string) error {
	if err := validateAgeKey(agePubkey); err != nil {
		return err
	}
	if accountID == "" {
		return ErrInvalidInput
	}
	if err := s.ensureBYOTable(); err != nil {
		return fmt.Errorf("keydir: byo migrate: %w", err)
	}

	fp := byoFingerprint(agePubkey)
	now := time.Now().UTC().Format(time.RFC3339)

	s.mu.Lock()
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO byo_pubkeys (account_id, age_pubkey, fingerprint, uploaded_at, rotation_count)
		VALUES (?, ?, ?, ?, 1)
		ON CONFLICT(account_id) DO UPDATE SET
		    age_pubkey     = excluded.age_pubkey,
		    fingerprint    = excluded.fingerprint,
		    uploaded_at    = excluded.uploaded_at,
		    rotation_count = rotation_count + 1`,
		accountID, agePubkey, fp, now)
	s.mu.Unlock()
	if err != nil {
		return fmt.Errorf("keydir: put byo key: %w", err)
	}
	return nil
}

// GetBYOKey returns the current age X25519 public key for an account.
// Returns ErrBYOKeyNotFound if the account has no registered BYO key.
func (s *SQLStore) GetBYOKey(ctx context.Context, accountID string) (string, error) {
	if err := s.ensureBYOTable(); err != nil {
		return "", fmt.Errorf("keydir: byo migrate: %w", err)
	}
	row := s.db.QueryRowContext(ctx,
		`SELECT age_pubkey FROM byo_pubkeys WHERE account_id = ?`, accountID)
	var pubkey string
	if err := row.Scan(&pubkey); errors.Is(err, sql.ErrNoRows) {
		return "", ErrBYOKeyNotFound
	} else if err != nil {
		return "", fmt.Errorf("keydir: get byo key: %w", err)
	}
	return pubkey, nil
}

// ListBYOKeyHistory returns the key history for an account. In the current
// single-key schema this returns the current key (rotation_count=N shows how
// many rotations have occurred). A future migration may add a history table.
func (s *SQLStore) ListBYOKeyHistory(ctx context.Context, accountID string) ([]BYOHistoryEntry, error) {
	if err := s.ensureBYOTable(); err != nil {
		return nil, fmt.Errorf("keydir: byo migrate: %w", err)
	}
	row := s.db.QueryRowContext(ctx, `
		SELECT age_pubkey, fingerprint, uploaded_at, rotation_count
		FROM byo_pubkeys WHERE account_id = ?`, accountID)
	var (
		e     BYOHistoryEntry
		tsStr string
	)
	err := row.Scan(&e.AgePubkey, &e.Fingerprint, &tsStr, &e.RotationCount)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("keydir: list byo history: %w", err)
	}
	if t, terr := time.Parse(time.RFC3339, tsStr); terr == nil {
		e.UploadedAt = t
	}
	return []BYOHistoryEntry{e}, nil
}

// ---------------------------------------------------------------------------
// Validation + fingerprint helpers
// ---------------------------------------------------------------------------

// validateAgeKey checks that key is a non-empty string starting with "age1"
// (the bech32 prefix for age X25519 public keys). It does NOT do full bech32
// decoding — that is the responsibility of the age library at decrypt time.
func validateAgeKey(key string) error {
	key = strings.TrimSpace(key)
	if key == "" {
		return ErrInvalidAgeKey
	}
	if !strings.HasPrefix(key, "age1") {
		return ErrInvalidAgeKey
	}
	// Minimum plausible length: "age1" (4) + bech32 body (at least 10 chars).
	if len(key) < 14 {
		return ErrInvalidAgeKey
	}
	return nil
}

// byoFingerprint returns the first 16 hex chars of SHA-256 of the bech32 body
// (the key string with the "age1" prefix stripped).
func byoFingerprint(pubkey string) string {
	body := strings.TrimPrefix(pubkey, "age1")
	h := sha256.Sum256([]byte(body))
	return hex.EncodeToString(h[:])[:16]
}
