#!/usr/bin/env node
/**
 * vendor-apps.mjs — regenerate the self-hosted, same-origin JS bundles for the
 * installed OS apps that would otherwise load libraries from the esm.sh CDN.
 *
 * SOVEREIGNTY: a self-host / air-gapped Vulos OS must never depend on a
 * third-party CDN to open an app, and must not leak user activity to esm.sh.
 * The `sheets` and `text-editor` apps therefore ship their JS deps locally in
 * `apps/<id>/vendor/*.js`, referenced by a same-origin `<script type=importmap>`.
 *
 * This script installs the exact pinned versions, bundles each import-map
 * specifier with esbuild (code-splitting ON so shared deps like
 * @codemirror/state, @codemirror/view, yjs and lib0 stay single instances),
 * and copies the outputs into each app's vendor/ dir.
 *
 * LICENCES: minifying strips the `@license` banners out of the bundles, but the
 * MIT/BSD terms those banners carried still bind us — we redistribute this code
 * inside the Vulos image. So the script also writes each app's
 * `vendor/LICENSES/<pkg>.txt` (the real upstream licence file, copied out of the
 * package it installed) plus an `index.json` that gen-notices.mjs reads. The
 * bundles and their licences are therefore regenerated by the same command and
 * cannot drift apart.
 *
 * Usage:  node scripts/vendor-apps.mjs [--licenses-only]
 *   --licenses-only   refresh vendor/LICENSES/ without re-bundling the blobs
 *                     (no esbuild, existing vendor/*.js left untouched).
 * Requires: network access (npm install of the pinned versions) + npx esbuild.
 *
 * If you bump a version here, also bump the version in the matching app's
 * index.html importmap comment so the two stay in sync.
 */
import { execSync, execFileSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, writeFileSync, copyFileSync, readFileSync, readdirSync, rmSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { detectSPDX, LICENSE_FILENAMES } from './licensing/spdx.mjs'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const LICENSES_ONLY = process.argv.includes('--licenses-only')

// Import-map specifier -> pinned npm package@version. Output file is derived
// from the entry name (e.g. @lezer/highlight -> lezer-highlight.js).
const MODS = {
  'state':            '@codemirror/state@6.4.1',
  'view':             '@codemirror/view@6.34.3',
  'commands':         '@codemirror/commands@6.7.1',
  'language':         '@codemirror/language@6.10.3',
  'search':           '@codemirror/search@6.5.8',
  'autocomplete':     '@codemirror/autocomplete@6.18.4',
  'lint':             '@codemirror/lint@6.8.4',
  'theme-one-dark':   '@codemirror/theme-one-dark@6.1.2',
  'lang-javascript':  '@codemirror/lang-javascript@6.2.2',
  'lang-python':      '@codemirror/lang-python@6.1.6',
  'lang-html':        '@codemirror/lang-html@6.4.9',
  'lang-css':         '@codemirror/lang-css@6.3.1',
  'lang-json':        '@codemirror/lang-json@6.0.1',
  'lang-markdown':    '@codemirror/lang-markdown@6.3.1',
  'lang-sql':         '@codemirror/lang-sql@6.8.0',
  'lang-xml':         '@codemirror/lang-xml@6.1.0',
  'lezer-highlight':  '@lezer/highlight@1.2.1',
  'yjs':              'yjs@13.6.18',
  'y-websocket':      'y-websocket@1.5.4',
  'y-codemirror.next': 'y-codemirror.next@0.3.5',
  'lib0':             'lib0@0.2.99',
}

// Which entry names each app consumes (transitive shared chunks are copied too).
const APP_ENTRIES = {
  'sheets': ['yjs', 'y-websocket'],
  'text-editor': Object.keys(MODS),
}

// Third-party assets vendored as plain files rather than esbuild bundles
// (copied from the package's dist/). No bundling to do — but the licence still
// has to travel with the code, so they take part in the licence collection.
// apps/maps/vendor/leaflet/ = the dist/ directory of this package.
const APP_ASSETS = {
  'maps': ['leaflet@1.9.4'],
}

/** Every package directory under a node_modules tree, scoped names included. */
function* walkNodeModules(nmDir) {
  if (!existsSync(nmDir)) return
  for (const name of readdirSync(nmDir).sort()) {
    if (name === '.bin' || name === '.package-lock.json') continue
    if (name.startsWith('@')) {
      for (const sub of readdirSync(join(nmDir, name)).sort()) yield [`${name}/${sub}`, join(nmDir, name, sub)]
    } else {
      yield [name, join(nmDir, name)]
    }
  }
}

/**
 * Install `specs` into a throwaway dir and copy the licence file of every
 * package in the resulting closure into apps/<app>/vendor/LICENSES/.
 * The closure — not just the pinned top-level names — because the bundle
 * contains the transitive deps too (lib0 inside yjs, @lezer/* inside the
 * CodeMirror language packages, ...).
 */
function collectLicenses(app, specs) {
  const work = mkdtempSync(join(tmpdir(), `vulos-lic-${app}-`))
  try {
    writeFileSync(join(work, 'package.json'), JSON.stringify({ name: `lic-${app}`, private: true }))
    execFileSync('npm', ['install', '--no-save', '--no-audit', '--no-fund', ...specs], { cwd: work, stdio: 'inherit' })

    const outDir = join(repoRoot, 'apps', app, 'vendor', 'LICENSES')
    rmSync(outDir, { recursive: true, force: true })
    mkdirSync(outDir, { recursive: true })

    const index = []
    const noText = []
    for (const [name, dir] of walkNodeModules(join(work, 'node_modules'))) {
      const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
      const declared = typeof pkg.license === 'string' ? pkg.license : null
      const licFile = readdirSync(dir).filter((f) => LICENSE_FILENAMES.test(f)).sort()[0]
      if (!licFile) {
        // The package ships no licence file. Record what its publisher declares —
        // never substitute a licence text we did not get from the package itself.
        noText.push(`${name}@${pkg.version} (declares: ${declared || 'nothing'})`)
        index.push({ name, version: pkg.version, declared, spdx: null, file: null })
        continue
      }
      const text = readFileSync(join(dir, licFile), 'utf8')
      const file = `${name.replace(/[@/]/g, '_').replace(/^_/, '')}.txt`
      writeFileSync(join(outDir, file), text)
      index.push({ name, version: pkg.version, declared, spdx: detectSPDX(text), file })

      // When the package is vendored as its own directory of plain files
      // (apps/maps/vendor/leaflet/), put the licence inside that directory too —
      // that is where anyone looking at the blob will look for it.
      const assetDir = join(repoRoot, 'apps', app, 'vendor', name)
      if (existsSync(assetDir)) writeFileSync(join(assetDir, 'LICENSE'), text)
    }
    index.sort((a, b) => a.name.localeCompare(b.name))
    writeFileSync(join(outDir, 'index.json'), JSON.stringify(index, null, 2) + '\n')
    console.log(`apps/${app}/vendor/LICENSES: ${index.length} packages in the install closure`)
    if (noText.length) {
      console.warn(`  NOTE: no licence file shipped upstream by: ${noText.join(', ')}`)
      console.warn('  Recorded with the publisher-declared licence only. If such a package ends up')
      console.warn('  in a shipped bundle, obtain its licence text before release.')
    }
  } finally {
    rmSync(work, { recursive: true, force: true })
  }
}

if (LICENSES_ONLY) {
  for (const [app, entries] of Object.entries(APP_ENTRIES)) {
    collectLicenses(app, entries.map((e) => MODS[e]))
  }
  for (const [app, specs] of Object.entries(APP_ASSETS)) collectLicenses(app, specs)
  console.log('done (licences only — bundles untouched).')
  process.exit(0)
}

const bare = (v) => v.replace(/^(@[^/]+\/)?[^@]+@.*/, (_, s) => (s || '') + v.split('@').slice(s ? 1 : 0).join('@').split('@')[0])

const work = mkdtempSync(join(tmpdir(), 'vulos-vendor-'))
console.log('workdir:', work)
try {
  writeFileSync(join(work, 'package.json'), JSON.stringify({ name: 'vendor', private: true, type: 'module' }))
  const pkgs = Object.values(MODS).map((p) => `"${p}"`).join(' ')
  console.log('installing pinned versions…')
  execSync(`npm install --no-save ${pkgs}`, { cwd: work, stdio: 'inherit' })

  const entriesDir = join(work, 'entries')
  mkdirSync(entriesDir, { recursive: true })
  for (const [name, pkgv] of Object.entries(MODS)) {
    const pkg = pkgv.replace(/@[^@]+$/, '').replace(/^(@[^/]+\/.+)@.*/, '$1')
    // strip trailing @version (handles scoped names)
    const clean = pkgv.replace(/@(\d[^@]*)$/, '')
    writeFileSync(join(entriesDir, `${name}.js`), `export * from '${clean}';\n`)
  }

  const outDir = join(work, 'out')
  console.log('bundling with esbuild…')
  execSync(`npx --yes esbuild entries/*.js --bundle --format=esm --splitting --outdir=out --minify --log-level=warning`, { cwd: work, stdio: 'inherit' })

  // Reachability: for each app, copy its entry files + their relative chunk closure.
  const readDeps = (dir, file, seen = new Set()) => {
    if (seen.has(file)) return seen
    seen.add(file)
    const src = readFileSync(join(dir, file), 'utf8')
    for (const m of src.matchAll(/(?:from|import)"(\.\/[^"]+)"/g)) readDeps(dir, m[1].slice(2), seen)
    return seen
  }
  for (const [app, entries] of Object.entries(APP_ENTRIES)) {
    const closure = new Set()
    for (const e of entries) for (const f of readDeps(outDir, `${e}.js`)) closure.add(f)
    const vendorDir = join(repoRoot, 'apps', app, 'vendor')
    rmSync(vendorDir, { recursive: true, force: true })
    mkdirSync(vendorDir, { recursive: true })
    for (const f of closure) copyFileSync(join(outDir, f), join(vendorDir, f))
    console.log(`apps/${app}/vendor: ${closure.size} files`)
  }
  console.log('done. Verify no esm.sh references remain in apps/*/index.html.')
} finally {
  rmSync(work, { recursive: true, force: true })
}

// The bundles were just rewritten; refresh the licences that must ship with them.
for (const [app, entries] of Object.entries(APP_ENTRIES)) {
  collectLicenses(app, entries.map((e) => MODS[e]))
}
for (const [app, specs] of Object.entries(APP_ASSETS)) collectLicenses(app, specs)
console.log('licences refreshed. Regenerate the notices: node scripts/licensing/gen-notices.mjs')
